### ISSUE TITLE
What is the unity of the Ruler tool?

### ISSUE THREAD

**Issue by XaloDev** [ivmartel/dwv#1026]
What is the unit of the Ruler tool? I was using this tool, but i have no assurance of what is the unit of measurement.

**Comment by ivmartel** [comment]
If the data has values for the `PixelSpacing` (0028, 0030) or `ImagerPixelSpacing` (0018, 1164) then the unit will be mm (see [part03/sect_C.7.6.2](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.2.html#table_C.7-10)).
Otherwise the unit is pixels. It's true that the viewer does not provide a unit for this case, this could be made more explicit.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
