### ISSUE TITLE
How can i display the ruler unit of measurement? 

### ISSUE THREAD

**Issue by mariocesarf** [ivmartel/dwv#1148]
I want to display the ruler unit of measurement when use the Ruler tool, showing alongside the number, how can i do this?

**Comment by XaloDev** [comment]
So what is the code needed to do this?

**Comment by XaloDev** [comment]
I want to put a unit after the number showing, like "150mm" rather than just "150"

**Comment by ivmartel** [comment]
Is it echo (modality: US) or not?

**Comment by XaloDev** [comment]
Imperial system, meters

**Comment by ivmartel** [comment]
Most image modalities (CT, MR...) include pixel spacing in the dicom header. When present, the viewer will use this tag to translate a number of pixels to a distance in mm. For the modality US (echography), this spacing is not present, the viewer cannot do the translation, that's why it does not show a unit next to a measurement.

**Comment by XaloDev** [comment]
I have pixel spacing in mine 
![image](https://user-images.githubusercontent.com/73499961/164759549-6676c854-c0fb-4c76-9b01-90a14781e605.png)

**Comment by XaloDev** [comment]
If i have this, i cant custom the size of the canvas?

**Comment by ivmartel** [comment]
You can, the viewer will try to fit the data in it as best as it can.

**Comment by XaloDev** [comment]
So, having the PixelSpacing, how do i show the "mm" or "cm"?

**Comment by ivmartel** [comment]
The ruler uses the `dwv.math.Line` class, its [quantify](https://github.com/ivmartel/dwv/blob/v0.30.8/src/math/line.js#L222) method will return the length with unit if the length is not null. Are you using the default ruler tool and it is not showing the unit?

**Comment by XaloDev** [comment]
Yes, I’m using the default ruler

**Comment by XaloDev** [comment]
I'm using, 
this.state.dwvApp.setTool("Draw")
this.state.dwvApp.setDrawShape("Ruler")

**Comment by XaloDev** [comment]
The console say nothing and 
![image](https://user-images.githubusercontent.com/73499961/165097391-da79aa3f-f976-4a54-8091-46269a095ef4.png)

**Comment by XaloDev** [comment]
The unit is millimeter?

**Comment by ivmartel** [comment]
yes, it should be millimeter.

Now I get your problem, you are in a setup similar to the one of dwv-react, no? In these demos, the translation files are not loaded. The quantify method I mentioned above, returns an object with the unit that comes from a translation file, since there is none, it comes back empty. I still need to find an way to includes these translations... All help accepted, if you know how react handles this, I'm interested!

**Comment by XaloDev** [comment]
Yes, is a react project, i'll try too, if i can resolve the problem i'll send to you

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
