### ISSUE TITLE
Not a valid DICOM file (no magic DICM word found) on JPEG image

### ISSUE THREAD

**Issue by christianesperar** [ivmartel/dwv#125]

**Comment by IanYates** [comment]
It's worth checking the file...  Is the magic DICM string present?  Are you able to share the file?

**Comment by christianesperar** [comment]
Sent to your email :)

**Comment by IanYates** [comment]
That was just a JPEG....  It needs to be a DICOM file (which could well contain a single JPEG image).  Refer: http://dicomiseasy.blogspot.com.au/2011/10/introduction-to-dicom-chapter-1.html

**Comment by christianesperar** [comment]
But the problem is some jpeg file works no problem by using  this.

**Comment by ivmartel** [comment]
You can load raw jpg/png images with dwv (see the examples at the bottom of the demo page). It should work with v0.8.0 and with the current master.
But the error message you get should not happen... What version are you using? Can you send me the file?

**Comment by christianesperar** [comment]
We used current version. File sent to your email.

**Comment by ivmartel** [comment]
The image you sent loads OK for me with the latest code. It is big, so it takes time, but it does not give me any error message. Which browser are you using?

**Comment by ivmartel** [comment]
Ok, now I get it! You get this error when loading the jpeg file from a link. When data comes from a link, I use the file's [signature](http://en.wikipedia.org/wiki/List_of_file_signatures) to guess what type it is, see [url.js#L75](https://github.com/ivmartel/dwv/blob/master/src/io/url.js#L75).
You will not get this error when loading it from a file since I get the info from the file object the html passed.
I can look for a more robust way of guessing file types. Out of curiosity, where do these files come from?

**Comment by christianesperar** [comment]
I see. So this is not possible at the moment right? We are trying to integrate this viewer to our project and the tester gave us this feedback.
