### ISSUE TITLE
Additional Examples of Displaying DICOM

### ISSUE THREAD

**Issue by cancan101** [ivmartel/dwv#138]
There is a quite a jump in complexity from [this example](http://jsfiddle.net/ivmartel/LteeL0gf/):
```js
// create the dwv app
var app = new dwv.App();
// initialise with the id of the container div
app.init({
    "containerDivId": "dwv"
});
// load dicom data
app.loadURL(["http://x.babymri.org/?53320924&.dcm"]);
```

to [this example](https://github.com/ivmartel/dwv/blob/gh-pages/demo/stable/viewers/mobile/applauncher.js) where even the call to `app.loadURL` is buried.

It would be great to have a clean example of of using DWV to show a DICOM image allow with the basic set of controls.

**Comment by ivmartel** [comment]
Well received! I would like to have more time to add fiddles... A simpler intermediate example is the '[simple](https://github.com/ivmartel/dwv/blob/master/viewers/simple/applauncher.js)' viewer. `app.loadURL` is burried because these are standalone apps, they take the url from the address or via a specific gui.

**Comment by ivmartel** [comment]
Added (short) comments to the API page...
