### ISSUE TITLE
Can i integrate Socket.io with dwv 

### ISSUE THREAD

**Issue by srivastavadevesh124** [ivmartel/dwv#1415]
I want to integrate socket.io features with dwv so that whenever users connec to the same socket.io event and if one user uploads a dicom image then it should show in the viewer of other users who are connected too . is it possible ? please help

**Comment by ivmartel** [comment]
Sorry, I have no experience with socket.io...

But this seems to be more related to the storage of your dicom files and its connection to the client rather than the viewer.

**Comment by ychyss** [comment]
I think you @srivastavadevesh124  need not only socket but also webRTC. In fact, I also need this feature in my project(and doing for this), if @ivmartel  can consider this new feature, we will very appreciate for that. :-)

The webRTC is used for the communication between clients. For example, web online video and audio. The key feature I need is multi user ops in sync on Viewer. Just like remote control but DICOM Viewer so that they can share not only DICOM images(maybe one DICOM cloud storage), but also annotations, reports and other datas.

**Comment by ivmartel** [comment]
Closing for now, please follow #119 for progress.
