### ISSUE TITLE
Jpeg decoder loads multiple times in browser

### ISSUE THREAD

**Issue by dearshivaramallva** [ivmartel/dwv#318]
*decode-jpegloss.js* loads multiple times in browser resulting to eat more bandwidth.

![2](https://cloud.githubusercontent.com/assets/2039058/23579582/6530b096-0116-11e7-98aa-fc1703e298c4.PNG)

I'm loading jpeg decoders like below
```
dwv.image.decoderScripts = {
    "jpeg2000": "./scripts/libs/ext/pdfjs/decode-jpeg2000.js",
    "jpeg-lossless": "./scripts/libs/ext/rii-mango/decode-jpegloss.js",
    "jpeg-baseline": "./scripts/libs/ext/pdfjs/decode-jpegbaseline.js"
};
```
Do we need to include all these above js files?

Kindly help please?

**Comment by ivmartel** [comment]
This is the normal behaviour since decoders use [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers). What you are seeing is each thread loading the decoder script. As long as you define the `dwv.image.decoderScripts` with the appropriate decoder, dwv will try to use it to decode the image using web workers. If it cannot find a decoder, it will decode without the web workers.
Regarding bandwidth, the decoder files are included in the `cache.manifest` (and used if the html begins with `<html manifest="cache.manifest">`) so they should not generate traffic.

**Comment by dearshivaramallva** [comment]
Thank you. I understand now, thanks!
