### ISSUE TITLE
thread.test.js fail ???

### ISSUE THREAD

**Issue by jiapei100** [ivmartel/dwv#319]
Hi, all:

I'm testing dwv, but met the following ERROR message:

> thread: Test ThreadPool. (1, 0, 1)Rerun14 ms
> Died on test #1     at ....../dwv/tests/utils/thread.test.js:13:7: Failed to construct 'Worker': Script at '....../dwv/tests/utils/worker.js' cannot be accessed from origin 'null'.@ 1 ms
> Source: 	
> Error: Failed to construct 'Worker': Script at '....../dwv/tests/utils/worker.js' cannot be accessed from origin 'null'.
>     at dwv.utils.WorkerThread.run (....../dwv/src/utils/thread.js:108:22)
>     at dwv.utils.ThreadPool.addWorkerTask (....../dwv/src/utils/thread.js:40:26)
>     at Object.<anonymous> (....../dwv/tests/utils/thread.test.js:53:14)
> Source: at ....../dwv/tests/utils/thread.test.js:13:7

Can anybody help please?

Cheers
Pei

**Comment by ivmartel** [comment]
This test fails if you run it locally on Chrome or related (Opera for example) because it forbids access to local files for the web workers. See this [paragraph](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Browser_compatibility) of the Mozilla web workers page.
So two solutions:
 * run it in Firefox or
 * run it from a local web server

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to reopen.
