### ISSUE TITLE
Dicom writer error: Offset is outside the bounds

### ISSUE THREAD

**Issue by rafasoyyo** [ivmartel/dwv#335]
From #264 
I cannot use Dicom Writer 
It always throws the error: Offset is outside the bounds of the DataView.
Maybe I am doing something wrong...
I have attached a file with my code
[writer.zip](https://github.com/ivmartel/dwv/files/963995/writer.zip)

**Comment by ivmartel** [comment]
The [dicomWriter.test](https://github.com/ivmartel/dwv/blob/master/tests/dicom/dicomWriter.test.js) are passing and I can anonymise the `dwv-test-anonymise.dcm` data using the anonymiser html page.

Now the DICOM support for the writer is limited, maybe the data you are using was not tested, could you share some?

About your code, the file writer takes a blob as input not the raw buffer. Check out the anonimyser code.

**Comment by ivmartel** [comment]
Hi @rafasoyyo, did you make any progress on this one?

**Comment by yulia-tue** [comment]
Hi @ivmartel, 
I actually have a question about writer support. Currently it only allows syntax 1.2.840.10008.1.2.1 (Explicit VR - Little Endian). 
What I did was, I took a file with 1.2.840.10008.1.2.4.91 (JPEG 2000 Image Compression), parsed it with DicomParser, then created a file with DicomWriter and parsed it again. Then I compared both dicomElementsSets with http://unexpected.js.org/ (because it handles large arrays of pixel data better). 
Since both dicomElementsSets are identical, specifically, both pixel data arrays are equal, I assumed that this syntax can be supported as well. 

What do you think? I could create a merge request for this test, if you like. 

Best,

Yulia

**Comment by ivmartel** [comment]
@yulia-tue, it seems reasonable, I create #343 to record the change.

**Comment by rafasoyyo** [comment]
Sorry @ivmartel, I had no time. I will have a look this weekend and I will notify you what append.

**Comment by rafasoyyo** [comment]
Hi @ivmartel, you were right, DicomWriter works fine but my dicom is not supported.
I have solved my needs on server side using dcmtk, but anyway I think it would be a nice feature, so let my know If I can help you or @yulia-tue just to improve DicomWriter support.

**Comment by ivmartel** [comment]
Ok, so I close this issue. The work needed to improve the writer has been described in #343.
