### ISSUE TITLE
Multiple .dcm app load issue

### ISSUE THREAD

**Issue by FPChris** [ivmartel/dwv#411]
I have 5 dcm thumbnails in a row. If the user clicks on a thumbnail I overlay a light box div. The light box opens, the app is created then a dcm is loaded. The user can close the light box in order to view the next dcm and so on.

Problem. If I start loading .dcm #1 then the user closes the light box before it finished loading, clicks on
the next thumbnail and starts loading .dcm #2. BOTH seem to be loading in the background.
I get a percentage display that rapidly alternates between two percents 5%-45% ...6%-48% etc. 
It seems .dcm #1 finishes and does nothing. But is confusing on screen and I worry about the memory.

**Comment by ivmartel** [comment]
It's true there is no cancel option for a download you would like to stop. This is why you see the first download finish and do nothing. And this messes up the progress bar since it is receiving updates from two downloads. 
With a cancel feature, when the user clicks on another thumbnail, you would be able to cancel the first download and launch the new one. I created #412 for this feature,

**Comment by FPChris** [comment]
Thanks. Much appreciated.

**Comment by ivmartel** [comment]
Closing this issue, please comment on #412.
