### ISSUE TITLE
Frame rate on multiframes

### ISSUE THREAD

**Issue by BrianMcRails** [ivmartel/dwv#476]
Thanks for the updates to make this importable, started using it in a React project yesterday and it works great!

Have a question about the mutliframes, what determines the frame rate when you play them by double clicking? Is it just a static FPS always Or is it possible to adjust? Wondering if it would be possible to use the value from the recommended display frame rate tag for the playback speed.

**Comment by ivmartel** [comment]
Perfect, thanks for the feedback about dwv-react.

For the moment the frame rate is fixed, but it's because I did not know about the `RecommendedDisplayFrameRate` tag (ref: [table_C.7-13](http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_C.7.html#table_C.7-13)). It could be added to the meta data of the image and, if present, used when playing.

**Comment by BrianMcRails** [comment]
I think I see where the changes are needed, I’ll submit a PR later today for you to review.

**Comment by ivmartel** [comment]
Closed with #477. Thanks @BrianMcRails for the PR!
