### ISSUE TITLE
Best Way to Integrate Full Viewer

### ISSUE THREAD

**Issue by tpitman** [ivmartel/dwv#496]
At this URL there is an awesome full version of the DWV viewer. I would like to have all of the same functionality in my viewer. Can someone give me a tutorial or set of steps to integrate all of these features into my own site?

https://ivmartel.github.io/dwv-jqui/demo/stable/index.html

If this has already been answered, sorry I missed it. Please point it out.

**Comment by ivmartel** [comment]
Sorry, no tutorial or step by step... The main difference with the simplistic viewer is that this one (and the dwv-jqmobile one) use some default gui classes defined by dwv. Check out for example the window-level at [tools.js#L85](https://github.com/ivmartel/dwv/blob/develop/src/gui/tools.js#L85). These classes can be overwritten in appgui files (as for dwv-jqui [appgui.js](https://github.com/ivmartel/dwv-jqui/blob/master/src/appgui.js)). 

The aim was to simplify integrations, I'm not too sure about it any more, since integrations can be very different, it could be their responsibility to define completely the gui...

**Comment by ivmartel** [comment]
I hope I was clear. Closing for now, feel free to comment / reopen if you need.
