### ISSUE TITLE
windows level Mechanisms and canvas apply

### ISSUE THREAD

**Issue by ddbxyrj** [ivmartel/dwv#518]
：）

Dicom pixel data may include 10 bits or 16bits. However as far as I known, web browser canvas may only interpret all data into 8bits picture.  Is this true?
If we take an 16 bits image, shrink its windows wild into 8 bits(2^16->2^8). Is it safe to say it can be show  on an web canvas without color lost? I think with calculation of color mapping, it could be down.
thank you.

**Comment by ddbxyrj** [comment]
If I want to just do windows level and wild adjustment of a image(png jpe). I will get byte data, and draw it into canvas, take pixel data from canvas, do the calculation to change color of  pixel which out range of windows wild, draw the pixel again.

**Comment by ivmartel** [comment]
You're right, the storage does not allow to view the full range in all its detail. This is where the window/level comes into play: it narrows the range so that you see more details. In dwv, this is handled in the [view](https://github.com/ivmartel/dwv/blob/v0.23.5/src/image/view.js) class.
Thinking about it, it would be nice to tell the user that the range is or isn't displayed entirely, not sure if there is something in the standard about it. 

Kind of related is this doc from the standard: [Part 14: Grayscale Standard Display Function](http://dicom.nema.org/Dicom/2011/11_14pu.pdf).

**Comment by ddbxyrj** [comment]
thank you
