### ISSUE TITLE
Error when starting local server

### ISSUE THREAD

**Issue by piddnad** [ivmartel/dwv#652]
When running `yarn run start`, an error occurs:

```
yarn run v1.13.0
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So I went to `package.json` and add something like `"start": "grunt start",` in scripts, but still didn't work. 

Who can tell me how to launch the tests on a local server? Thank you!

**Comment by ivmartel** [comment]
You are right, there is no start script. That's intentional since you cannot really start the lib/viewer, what you can do is launch the test that include a simple viewer. For real viewers, check out the [example and integrations](https://github.com/ivmartel/dwv/wiki/Examples#viewers-and-integrations).

**Comment by piddnad** [comment]
> You are right, there is no start script. That's intentional since you cannot really start the lib/viewer, what you can do is launch the test that include a simple viewer. For real viewers, check out the [example and integrations](https://github.com/ivmartel/dwv/wiki/Examples#viewers-and-integrations).

Got it. Thank you! :)

**Comment by ivmartel** [comment]
Ok, closing. Feel free.to comment if you need.
