### ISSUE TITLE
How can i call the functions defined in dwv.js file in the html page like for example (this.onChangeFiles) ?

### ISSUE THREAD

**Issue by amine-semrani** [ivmartel/dwv#659]

**Comment by ivmartel** [comment]
You must create the app object (`var dwvApp = new dwv.App();`) and make it available where you need it so that you can call methods on it, for example the `onChangeFiles` one.

Check out the [dwv-simplistic](https://github.com/ivmartel/dwv-simplistic) repo for an example, the app is created (in [applauncher.js](https://github.com/ivmartel/dwv-simplistic/blob/master/src/applauncher.js)) and provided to a gui class ([appgui.js](https://github.com/ivmartel/dwv-simplistic/blob/master/src/appgui.js)) that then can call methods on it.

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment if you need.
