### ISSUE TITLE
Request Error: An error occurred while downloading 'SignedURL' (http status: 0)

### ISSUE THREAD

**Issue by rawl05** [ivmartel/dwv#697]
The DICOM viewer gives me **Request Error: An error occurred while downloading 'SignedURL' (http status: 0)** when I try to load images from GCP into the viewer. However, this error is not for all Series.
In the console the error shown is: **Failed to load resource: net::ERR_HTTP2_FLOW_CONTROL_ERROR**. This error occurs only for loading Series (the series gets loaded, but the pop-ups stay) and when i try to load single image from same series it loads. 

![output](https://user-images.githubusercontent.com/37844947/72883915-37f65500-3d2b-11ea-94d7-8ed1b6ce7938.jpg)
![example-1](https://user-images.githubusercontent.com/37844947/72883916-37f65500-3d2b-11ea-9bd0-1781ae169ed5.jpg)

**Comment by ivmartel** [comment]
Are you using the Google drive app? How many files are you trying to load and how big are they?

**Comment by rawl05** [comment]
I'm trying to load series of signed urls from Google Cloud Storage Bucket(Multi-regional) into the loadURLs() method. I'm trying to load a Series with 50 Images with each image not more than 1 Mb.
Is there way possible to handle these errors outside dwv.js ?

**Comment by ivmartel** [comment]
This looks like a reasonable http request. Does pasting the data link in a browser give the same error?

**Comment by rawl05** [comment]
Pasting the link in the browser downloads the image.

**Comment by ShinRai1090** [comment]
@ivmartel facing same issue here... is there a way to hook into the error mechanism to display our own custom messages (with custom displays) instead of the bare bone browser alerts thrown by the viewer?

**Comment by ivmartel** [comment]
You're right #562 is about letting the client handle errors. While waiting to 0.27 (should be out soon), the only thing I see is to manually change/build dwv...

**Comment by ShinRai1090** [comment]
> You're right #562 is about letting the client handle errors. While waiting to 0.27 (should be out soon), the only thing I see is to manually change/build dwv...

@ivmartel I can try that, have already forked the project. Could you guide us as to where / how we can make the change so as to make this makeshift implementation to show custom messages from the client. Will definitely help us a lot :)

**Comment by ivmartel** [comment]
Check out #562, the current code includes the change you want. 

Otherwise, if you are in a timeline that has the `handleError` method in `application.js`, you just need to remove the call to `alert` and fire an event with `fireEvent({type:"event-name", error: error})`. From your client, add a listener to this new event and handle as you like.

**Comment by ShinRai1090** [comment]
> Check out #562, the current code includes the change you want.
> 
> Otherwise, if you are in a timeline that has the `handleError` method in `application.js`, you just need to remove the call to `alert` and fire an event with `fireEvent({type:"event-name", error: error})`. From your client, add a listener to this new event and handle as you like.

@madhugore1

**Comment by Mamta92** [comment]
I'm also facing a similar issue. Say I have around 100 images signed urls that needs to be passed to the DICOM viewer. Is there a possibility of loading these images in batches to the viewer to not bombard the http request? Not sure but I think 100 http calls made simultaneously to fetch these 100 images are creating some kind of problem.

**Comment by ivmartel** [comment]
A note about the initial error `net::ERR_HTTP2_FLOW_CONTROL_ERROR`: "FLOW_CONTROL_ERROR (0x3): The endpoint detected that its peer violated the flow-control protocol." ([ref](https://http2.github.io/http2-spec/#rfc.section.7)).

Since you mention GCP, you can create batch request from their api, see [Making Batch Requests](https://github.com/google/google-api-javascript-client/blob/master/docs/batch.md). I implemented it in dwv-jqmobile, see [google.js#L214](https://github.com/ivmartel/dwv-jqmobile/blob/v0.3.0/src/google.js#L214)

**Comment by ivmartel** [comment]
#780 now allows to make requests by batch. I hope it helps fix your issue. Closing for now, feel free to comment if you need.
