### ISSUE TITLE
Change strokeWidth dynamically with the scale

### ISSUE THREAD

**Issue by alvarogardev** [ivmartel/dwv#733]
Hi, it is possible to modify the strokeWidth (with the value of dividing the current StrokeWidth by the current scale) before painting a ROI or a line.

Thnks!

**Comment by ivmartel** [comment]
You are right, something must be wrong since the style object used to get the stroke width should handle the scale, except if nobody told him, I'll check this.

**Comment by ivmartel** [comment]
This issue implies too much changes for the 0.27.1 patch release. Moved to 0.28.

**Comment by ivmartel** [comment]
Ok, I had a closer look at this one. Nothing went wrong, I think the behaviour is the same since #145. Konva handles the zoom of its shapes when the stage is scaled. 

Konva provides a property for scaling or not the stroke of a shape: `strokeScaleEnabled` ([ref](https://konvajs.org/api/Konva.Shape.html#strokeScaleEnabled__anchor)), I'll add it to shapes.

There does not seem to be a similar flag for text, see [konva/issues/631](https://github.com/konvajs/konva/issues/631).
